# Generated by Selenium IDE

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains


class TestTestdemo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_testdemo(self):
    self.driver.get("https://ceshiren.com/")
    self.driver.set_window_size(1070, 824)
    self.driver.find_element(By.LINK_TEXT, "所有分类").click()
    time.sleep(5)
    element = self.driver.find_element(By.LINK_TEXT, "所有分类")
    # get_attribute获取元素标签的内容
    result = element.get_attribute('class')
    assert 'active' == result
